services:

  front-back-end:
    build:
      context: web
    container_name: web
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "4200:3000"
    command: npm run dev

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - node-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  node-network:
    driver: bridge

volumes:
  postgres_data:
