# Use a slim Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app
COPY app ./app

# Expose port (Flask default 5000)
EXPOSE 5000

# Run the server
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
