/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stacy Jnsn (https://sketchfab.com/stacy_666)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/witchs-table-56db8f27299b423985b503e96513a450
Title: Witch's Table
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Fire1009_0: THREE.SkinnedMesh
    Fire1007_0: THREE.SkinnedMesh
    Fire1006_0: THREE.SkinnedMesh
    Fire1005_0: THREE.SkinnedMesh
    Fire1004_0: THREE.SkinnedMesh
    Fire1003_0: THREE.SkinnedMesh
    Fire1002_0: THREE.SkinnedMesh
    Table_0: THREE.Mesh
    Mortar_0: THREE.Mesh
    Pot_0: THREE.Mesh
    Potion2_0: THREE.Mesh
    Potion1_0: THREE.Mesh
    Candle6_0: THREE.Mesh
    Candle2_0: THREE.Mesh
    Candle7_0: THREE.Mesh
    Candle5_0: THREE.Mesh
    Candle8_0: THREE.Mesh
    Stand_0: THREE.Mesh
    Candle3_0: THREE.Mesh
    Candle9_0: THREE.Mesh
    Candle1_0: THREE.Mesh
    Candle4_0: THREE.Mesh
    Herbarium1_0: THREE.Mesh
    ['Herbarium2(1)_0']: THREE.Mesh
    ['Herbarium2(2)_0']: THREE.Mesh
    Fire1_0: THREE.SkinnedMesh
    Fire1001_0: THREE.SkinnedMesh
    Book_1: THREE.Mesh
    Armature10_rootJoint: THREE.Bone
    Armature8_rootJoint: THREE.Bone
    Armature7_rootJoint: THREE.Bone
    Armature6_rootJoint: THREE.Bone
    Armature5_rootJoint: THREE.Bone
    Armature4_rootJoint: THREE.Bone
    Armature3_rootJoint: THREE.Bone
    Armature1_rootJoint: THREE.Bone
    Armature2_rootJoint: THREE.Bone
  }
  materials: {
    ['None.022']: THREE.MeshStandardMaterial
    ['None.020']: THREE.MeshStandardMaterial
    ['None.019']: THREE.MeshStandardMaterial
    ['None.018']: THREE.MeshStandardMaterial
    ['None.017']: THREE.MeshStandardMaterial
    ['None.016']: THREE.MeshStandardMaterial
    ['None.001']: THREE.MeshStandardMaterial
    None: THREE.MeshStandardMaterial
    ['None.002']: THREE.MeshStandardMaterial
    ['None.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['None.005']: THREE.MeshStandardMaterial
    ['None.006']: THREE.MeshStandardMaterial
    ['None.007']: THREE.MeshStandardMaterial
    ['None.008']: THREE.MeshStandardMaterial
    ['None.009']: THREE.MeshStandardMaterial
    ['None.010']: THREE.MeshStandardMaterial
    ['None.011']: THREE.MeshStandardMaterial
    ['None.012']: THREE.MeshStandardMaterial
    ['None.013']: THREE.MeshStandardMaterial
    ['None.014']: THREE.MeshStandardMaterial
    ['None.004']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 01'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function WitchTable(props: React.JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/scene.gltf') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Armature10" position={[4.899, 1.723, 1.134]} scale={[0.169, 0.169, 0.106]}>
              <primitive object={nodes.Armature10_rootJoint} />
              <skinnedMesh
                name="Fire1009_0"
                geometry={nodes.Fire1009_0.geometry}
                material={materials['None.022']}
                skeleton={nodes.Fire1009_0.skeleton}
              />
              <group
                name="Fire1009"
                position={[-0.024, -0.004, 1.682]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.2, 0.905, 0.594]}
              />
            </group>
            <group name="Armature8" position={[5.226, 2.646, 2.055]} scale={[0.301, 0.301, 0.189]}>
              <primitive object={nodes.Armature8_rootJoint} />
              <skinnedMesh
                name="Fire1007_0"
                geometry={nodes.Fire1007_0.geometry}
                material={materials['None.020']}
                skeleton={nodes.Fire1007_0.skeleton}
              />
              <group
                name="Fire1007"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.175, 0.738, 0.567]}
              />
            </group>
            <group name="Armature7" position={[3.978, 2.649, 1.69]} scale={[0.291, 0.291, 0.183]}>
              <primitive object={nodes.Armature7_rootJoint} />
              <skinnedMesh
                name="Fire1006_0"
                geometry={nodes.Fire1006_0.geometry}
                material={materials['None.019']}
                skeleton={nodes.Fire1006_0.skeleton}
              />
              <group
                name="Fire1006"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.635]}
              />
            </group>
            <group name="Armature6" position={[-3.833, 0.498, 1.065]} scale={[0.171, 0.171, 0.107]}>
              <primitive object={nodes.Armature6_rootJoint} />
              <skinnedMesh
                name="Fire1005_0"
                geometry={nodes.Fire1005_0.geometry}
                material={materials['None.018']}
                skeleton={nodes.Fire1005_0.skeleton}
              />
              <group
                name="Fire1005"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.686]}
              />
            </group>
            <group name="Armature5" position={[-4.879, 0.896, 1.419]} scale={[0.205, 0.205, 0.129]}>
              <primitive object={nodes.Armature5_rootJoint} />
              <skinnedMesh
                name="Fire1004_0"
                geometry={nodes.Fire1004_0.geometry}
                material={materials['None.017']}
                skeleton={nodes.Fire1004_0.skeleton}
              />
              <group
                name="Fire1004"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.616]}
              />
            </group>
            <group name="Armature4" position={[-2.73, 1.355, 1.057]} scale={[0.233, 0.233, 0.146]}>
              <primitive object={nodes.Armature4_rootJoint} />
              <skinnedMesh
                name="Fire1003_0"
                geometry={nodes.Fire1003_0.geometry}
                material={materials['None.016']}
                skeleton={nodes.Fire1003_0.skeleton}
              />
              <group
                name="Fire1003"
                position={[-0.024, -0.004, 1.815]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.042, 0.654, 0.503]}
              />
            </group>
            <group name="Armature3" position={[-5.226, 2.173, 2.126]} scale={[0.284, 0.284, 0.178]}>
              <primitive object={nodes.Armature3_rootJoint} />
              <skinnedMesh
                name="Fire1002_0"
                geometry={nodes.Fire1002_0.geometry}
                material={materials['None.001']}
                skeleton={nodes.Fire1002_0.skeleton}
              />
              <group
                name="Fire1002"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.686]}
              />
            </group>
            <group
              name="Table"
              position={[0, 0.127, -1.764]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.981, 1, 0.939]}>
              <mesh
                name="Table_0"
                castShadow
                receiveShadow
                geometry={nodes.Table_0.geometry}
                material={materials.None}
              />
            </group>
            <group
              name="Mortar"
              position={[4.148, -1.484, 0.703]}
              rotation={[-Math.PI / 2, -0.561, -Math.PI]}
              scale={1.024}>
              <mesh
                name="Mortar_0"
                castShadow
                receiveShadow
                geometry={nodes.Mortar_0.geometry}
                material={materials['None.002']}
              />
            </group>
            <group
              name="Pot"
              position={[-0.133, 0.516, 0.502]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.269}>
              <mesh
                name="Pot_0"
                castShadow
                receiveShadow
                geometry={nodes.Pot_0.geometry}
                material={materials['None.003']}
              />
            </group>
            <group
              name="Potion2"
              position={[3.657, 1.035, 0.166]}
              rotation={[Math.PI / 2, -0.406, 0]}
              scale={1.057}>
              <mesh
                name="Potion2_0"
                castShadow
                receiveShadow
                geometry={nodes.Potion2_0.geometry}
                material={materials['Material.001']}
              />
            </group>
            <group
              name="Potion1"
              position={[2.35, 1.9, 0.077]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.458}>
              <mesh
                name="Potion1_0"
                castShadow
                receiveShadow
                geometry={nodes.Potion1_0.geometry}
                material={materials['None.005']}
              />
            </group>
            <group
              name="Candle6"
              position={[-1.904, 2.394, 1.383]}
              rotation={[-Math.PI / 2, -1.42, -Math.PI]}
              scale={0.506}>
              <mesh
                name="Candle6_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle6_0.geometry}
                material={materials['None.006']}
              />
            </group>
            <group
              name="Candle2"
              position={[-3.791, 2.015, 0.925]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.498, 0.306, 0.498]}>
              <mesh
                name="Candle2_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle2_0.geometry}
                material={materials['None.007']}
              />
            </group>
            <group
              name="Candle7"
              position={[3.969, 2.644, 0.774]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.432}>
              <mesh
                name="Candle7_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle7_0.geometry}
                material={materials['None.008']}
              />
            </group>
            <group
              name="Candle5"
              position={[-2.735, 1.355, 0.287]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.369}>
              <mesh
                name="Candle5_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle5_0.geometry}
                material={materials['None.009']}
              />
            </group>
            <group
              name="Candle8"
              position={[5.242, 2.64, 0.353]}
              rotation={[Math.PI / 2, -0.277, 0]}
              scale={[0.646, 0.779, 0.646]}>
              <mesh
                name="Candle8_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle8_0.geometry}
                material={materials['None.010']}
              />
            </group>
            <group
              name="Stand"
              position={[-0.135, 0.466, 0.516]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.439}>
              <mesh
                name="Stand_0"
                castShadow
                receiveShadow
                geometry={nodes.Stand_0.geometry}
                material={materials['None.011']}
              />
            </group>
            <group
              name="Candle3"
              position={[-4.855, 0.9, 0.311]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.499, 0.557]}>
              <mesh
                name="Candle3_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle3_0.geometry}
                material={materials['None.010']}
              />
            </group>
            <group
              name="Candle9"
              position={[4.868, 1.722, 0.285]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.235, 0.369, 0.235]}>
              <mesh
                name="Candle9_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle9_0.geometry}
                material={materials['None.009']}
              />
            </group>
            <group
              name="Candle1"
              position={[-5.233, 2.175, 0.348]}
              rotation={[-Math.PI / 2, -0.713, -Math.PI]}
              scale={[0.536, 0.779, 0.536]}>
              <mesh
                name="Candle1_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle1_0.geometry}
                material={materials['None.010']}
              />
            </group>
            <group
              name="Candle4"
              position={[-3.839, 0.496, 0.549]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.248}>
              <mesh
                name="Candle4_0"
                castShadow
                receiveShadow
                geometry={nodes.Candle4_0.geometry}
                material={materials['None.008']}
              />
            </group>
            <group
              name="Herbarium1"
              position={[1.999, -1.118, 0.253]}
              rotation={[Math.PI / 2, -1.352, 0]}
              scale={1.222}>
              <mesh
                name="Herbarium1_0"
                castShadow
                receiveShadow
                geometry={nodes.Herbarium1_0.geometry}
                material={materials['None.012']}
              />
            </group>
            <group
              name="Herbarium2(1)"
              position={[2.133, -1.679, 0.281]}
              rotation={[-Math.PI / 2, -0.724, Math.PI]}
              scale={0.662}>
              <mesh
                name="Herbarium2(1)_0"
                castShadow
                receiveShadow
                geometry={nodes['Herbarium2(1)_0'].geometry}
                material={materials['None.013']}
              />
            </group>
            <group
              name="Herbarium2(2)"
              position={[1.57, -1.603, 0.23]}
              rotation={[-Math.PI / 2, -1.338, -Math.PI]}
              scale={0.662}>
              <mesh
                name="Herbarium2(2)_0"
                castShadow
                receiveShadow
                geometry={nodes['Herbarium2(2)_0'].geometry}
                material={materials['None.013']}
              />
            </group>
            <group name="Armature1" position={[-1.914, 2.384, 2.311]} scale={[0.319, 0.319, 0.2]}>
              <primitive object={nodes.Armature1_rootJoint} />
              <skinnedMesh
                name="Fire1_0"
                geometry={nodes.Fire1_0.geometry}
                material={materials['None.014']}
                skeleton={nodes.Fire1_0.skeleton}
              />
              <group
                name="Fire1"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.686]}
              />
            </group>
            <group name="Armature2" position={[-3.79, 2.015, 1.547]} scale={[0.254, 0.254, 0.159]}>
              <primitive object={nodes.Armature2_rootJoint} />
              <skinnedMesh
                name="Fire1001_0"
                geometry={nodes.Fire1001_0.geometry}
                material={materials['None.014']}
                skeleton={nodes.Fire1001_0.skeleton}
              />
              <group
                name="Fire1001"
                position={[-0.024, -0.004, 2.054]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[1.42, 0.892, 0.686]}
              />
            </group>
            <group
              name="Book"
              position={[-3.408, -1.816, 0.23]}
              rotation={[-Math.PI / 2, -0.311, -Math.PI]}
              scale={0.636}>
              <mesh
                name="Book_1"
                castShadow
                receiveShadow
                geometry={nodes.Book_1.geometry}
                material={materials['None.004']}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.gltf')